export enum Categorie {
  INFORMATIQUE = 'INFORMATIQUE',

  MOBILIER = 'MOBILIER',

  CONSOMMABLE = 'CONSOMMABLE',

  MATERIELETACCESSOIRE = 'MATERIELETACCESSOIRE',

  ELECTRONIQUE = 'ELECTRONIQUE',

  EQUIPEMENT = 'EQUIPEMENT',

  MATERIEL_PEDAGOGIQUE = 'MATERIEL_PEDAGOGIQUE',

  MATERIEL_DIDACTIQUE = 'MATERIEL_DIDACTIQUE',
}
