export enum Filieres {
  AGRICULTURE = 'AGRICULTURE',

  BATIMENTS_ET_TRAVAUX_PUBLICS = 'BATIMENTS_ET_TRAVAUX_PUBLICS',

  MINES_ET_CARRIERES = 'MINES_ET_CARRIERES',

  MECANIQUE = 'MECANIQUE',

  ELECTROTECHNIQUE_ELECTRONIQUE_ENERGETIQUE = 'ELECTROTECHNIQUE_ELECTRONIQUE_ENERGETIQUE',

  HYDRAULIQUE = 'HYDRAULIQUE',

  STRUCTURE_METALLIQUE = 'STRUCTURE_METALLIQUE',

  STRUCTURE_PLASTIQUE = 'STRUCTURE_PLASTIQUE',

  ECONOMIE_GESTION_COMMERCE_ET_LOGISTIQUE = 'ECONOMIE_GESTION_COMMERCE_ET_LOGISTIQUE',

  AUTRES = 'AUTRES',
}
