export enum FonctionPersAd {
  PROVISEUR = 'PROVISEUR',

  SECRETAIRE = 'SECRETAIRE',

  DIRECTEURDESETUDES = 'DIRECTEURDESETUDES',

  AUDITEUR_INTERNE = 'AUDITEUR_INTERNE',

  CHEF_DESTRAVAUX = 'CHEF_DESTRAVAUX',

  COMPTABLE_DESMATIERES = 'COMPTABLE_DESMATIERES',

  INTENDANT = 'INTENDANT',

  RESPONSABLE_CELLULE_PEDAGOGIQUE = 'RESPONSABLE_CELLULE_PEDAGOGIQUE',

  SURVEIILLANT_GENERAL = 'SURVEIILLANT_GENERAL',

  SURVEILLANT_SIMPLE = 'SURVEILLANT_SIMPLE',

  INFIRMIER = 'INFIRMIER',

  COMPTABLE = 'COMPTABLE',

  ASSISTANTE_SOCIAL = 'ASSISTANTE_SOCIAL',

  ANIMATION_CULTUREL = 'ANIMATION_CULTUREL',

  BIBLIOTHECIAIRE = 'BIBLIOTHECIAIRE',

  AUTRES = 'AUTRES',
}
