export enum Type {
  CONSEIL_ETABLISSEEMENT = 'CONSEIL_ETABLISSEEMENT',

  CONSEIL_GESTION_ETABLISSEMENT = 'CONSEIL_GESTION_ETABLISSEMENT',

  CONSEIL_PEDAGOGIQUE = 'CONSEIL_PEDAGOGIQUE',

  COMMITE_GESTION = 'COMMITE_GESTION',
}
