package mefpai.gouv.sn.domain.enumeration;

/**
 * The Filieres enumeration.
 */
public enum Filieres {
    AGRICULTURE,
    BATIMENTS_ET_TRAVAUX_PUBLICS,
    MINES_ET_CARRIERES,
    MECANIQUE,
    ELECTROTECHNIQUE_ELECTRONIQUE_ENERGETIQUE,
    HYDRAULIQUE,
    STRUCTURE_METALLIQUE,
    STRUCTURE_PLASTIQUE,
    ECONOMIE_GESTION_COMMERCE_ET_LOGISTIQUE,
    AUTRES,
}
